version: "3.9"

services:  
  # Controller node is where ansible will be installed through bootstrap.sh
  # Image will be created with name "anslab/controller"
  # container will be created with name "anscontroller"
  controller:
    build: 
      context: .
      dockerfile: ubuntu/Dockerfile
    image: anslab/controller
    container_name: anscontroller
    hostname: anscontroller
#     volumes:
#       - /home/nixzie/Documents/project:/home/ansuser/project
    networks:
      - ansible_network
    pull_policy: build

  # Managed node is based on the image created from anslab/controller
  # container will be created with name "ansubuntu"
  ubuntu:
    image: anslab/controller
    container_name: ansubuntu
    hostname: ansubuntu
    networks:
      - ansible_network
    depends_on:
      - controller
    pull_policy: never

  # container will be created with name "ansalpine"
  alpine:
    build: 
      context: .
      dockerfile: alpine/Dockerfile
    image: anslab/alpine
    container_name: ansalpine
    hostname: ansalpine
    networks:
      - ansible_network
    pull_policy: build

  # container will be created with name "ansrocky"
  rocky:
    build: 
      context: .
      dockerfile: rocky/Dockerfile
    image: anslab/rocky
    container_name: ansrocky
    hostname: ansrocky
    networks:
      - ansible_network
    pull_policy: build
    

  # ansalpine:
  #   image: anslab/controller
  #   container_name: ansalpine
  #   hostname: ansalpine
  #   networks:
  #     - ansible_network
  #   depends_on:
  #     - controller

  # ansrocky:
  #   image: anslab/controller
  #   container_name: ansrocky
  #   hostname: ansrocky
  #   networks:
  #     - ansible_network
  #   depends_on:
  #     - controller


networks:
  ansible_network:
    driver: bridge
    name: anslab
